{{- if .Values.httpRoute.enabled -}}
{{- $svcPort := .Values.service.port -}}
# {{ $svcName := print .Chart.Name "-service" }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: clinic-api-route
  namespace: {{ .Release.namespace }}
spec:
  {{- with .Values.gateway.hostname }}
  hostnames:
  - {{ . | quote }}
  {{- end }}
  parentRefs:
  - name: {{ .Values.gateway.name }}
    kind: Gateway
    group: gateway.networking.k8s.io
    namespace: {{ .Release.namespace }}
  rules:
  - matches:
    - headers:
      {{- range .Values.httpRoute.headers }}
      - name: {{ .name | quote }}
        value: {{ .value | quote }}
      {{- end }}
      path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: "{{ .Chart.Name }}-service"
      port: {{ $svcPort }}
      kind: Service
      weight: 1
{{- end }}
