{{- if .Values.hooks.postsync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "clinic-booking-api.fullname" . }}-postsync
  labels:
{{ include "clinic-booking-api.labels" . | indent 4 }}
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: {{ default 0 .Values.hooks.postsync.backoffLimit }}
  template:
    metadata:
      labels:
{{ include "clinic-booking-api.selectorLabels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "clinic-booking-api.serviceAccountName" . }}
      restartPolicy: Never
      activeDeadlineSeconds: {{ default 300 .Values.hooks.postsync.activeDeadlineSeconds }}
      containers:
        - name: postsync
          image: "{{ .Values.hooks.postsync.image.repository }}:{{ .Values.hooks.postsync.image.tag }}"
          imagePullPolicy: {{ .Values.hooks.postsync.image.pullPolicy }}
          command: {{ toJson .Values.hooks.postsync.command }}
          env:
            - name: BASE_ENDPOINT
              value: "{{ .Values.hooks.postsync.baseEndpoint }}"
      {{- if .Values.hooks.postsync.image.pullSecrets }}
      imagePullSecrets:
{{- toYaml .Values.hooks.postsync.image.pullSecrets | indent 8 }}
      {{- end }}
{{- end }}
